### ISSUE TITLE
Understanding renomad output

### ISSUE THREAD

**Issue by durrantmm** [rcedgar/renomad#1]
Thank you for your work on this implementation of nomad. 

I would like to better understand the output. I analyzed 3 bioprojects of ~50 samples per project. There are hundreds of thousands to hundreds of millions of significant results when I run renomad. I don't see any P-values in the output files, and I'm also confused that all the anchor-targets are shown. Shouldn't each row be a single anchor along with a P-value of some kind, rather than the anchor and the target together?

I ran renomad with the following command:

```
renomad -joinp sample_paths.txt -maxp 0.05 -tsv3out renomad_output.tsv
```

And each time I ran it I got this warning:
```
WARNING: Option -maxp not used
```

Any advice?

**Comment by rcedgar** [comment]
The -maxp not used warning was a bug, I posted a fix (see changes to joinp.cpp). The output format is described in the README.md file, there is no P-value by design. The idea is that the expensive processing is done by renomad, downstream analysis such as P-values, effect size, contigs... can be done in other modules e.g. python.

**Comment by durrantmm** [comment]
Great, thank you. But it is calculating p-values when it applies the `-maxp` parameter? These results all meet some preliminary test of significance?

**Comment by rcedgar** [comment]
Yes, it calculates P-values, default is P<=0.05. You can safely use the version with the bug if you are happy with the default value.
